"""tambah field usia

Revision ID: 09254f69fedd
Revises: 0f59bb917711
Create Date: 2023-05-18 06:17:34.542948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09254f69fedd'
down_revision = '0f59bb917711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usia', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('usia')

    # ### end Alembic commands ###
