"""update table baru

Revision ID: 0f59bb917711
Revises: 1618a4197950
Create Date: 2023-05-09 11:58:15.248399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f59bb917711'
down_revision = '1618a4197950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id_question', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('jawaban', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Boolean(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
